using System;

namespace GMacBlade.cga0001
{
    /// <summary>
    /// This class represents an immutable blade in the cga0001 frame with arbitrary grade 
    /// (i.e. grade is determined at runtime) based on additive representation of the blade as a 
    /// linear combination of basis blades of the same grade (i.e. it's actually a k-vector representation).
    /// </summary>
    public sealed partial class cga0001Blade
    {
        private static double[] ApplyReflector_333(double[] coefs1, double[] coefs2)
        {
            var c = new double[10];
        
            //Bagin GMac Macro Code Generation, 2015-12-20T21:46:55.4091773+02:00
            //Macro: geometry3d.cga.ApplyReflector
            //Input Variables: 0 used, 20 not used, 20 total.
            //Temp Variables: 465 sub-expressions, 0 generated temps, 465 total.
            //Target Temp Variables: 32 total.
            //Output Variables: 10 total.
            //Computations: 1.26947368421053 average, 603 total.
            //Memory Reads: 1.98315789473684 average, 942 total.
            //Memory Writes: 475 total.
            //
            //Macro Binding Data: 
            //   result.#no^e1^e2# <=> <Variable> c[0]
            //   result.#no^e1^e3# <=> <Variable> c[1]
            //   result.#no^e2^e3# <=> <Variable> c[2]
            //   result.#e1^e2^e3# <=> <Variable> c[3]
            //   result.#no^e1^ni# <=> <Variable> c[4]
            //   result.#no^e2^ni# <=> <Variable> c[5]
            //   result.#e1^e2^ni# <=> <Variable> c[6]
            //   result.#no^e3^ni# <=> <Variable> c[7]
            //   result.#e1^e3^ni# <=> <Variable> c[8]
            //   result.#e2^e3^ni# <=> <Variable> c[9]
            //   v.#no^e1^e2# <=> <Variable> coefs1[0]
            //   v.#no^e1^e3# <=> <Variable> coefs1[1]
            //   v.#no^e2^e3# <=> <Variable> coefs1[2]
            //   v.#e1^e2^e3# <=> <Variable> coefs1[3]
            //   v.#no^e1^ni# <=> <Variable> coefs1[4]
            //   v.#no^e2^ni# <=> <Variable> coefs1[5]
            //   v.#e1^e2^ni# <=> <Variable> coefs1[6]
            //   v.#no^e3^ni# <=> <Variable> coefs1[7]
            //   v.#e1^e3^ni# <=> <Variable> coefs1[8]
            //   v.#e2^e3^ni# <=> <Variable> coefs1[9]
            //   mv.#no^e1^e2# <=> <Variable> coefs2[0]
            //   mv.#no^e1^e3# <=> <Variable> coefs2[1]
            //   mv.#no^e2^e3# <=> <Variable> coefs2[2]
            //   mv.#e1^e2^e3# <=> <Variable> coefs2[3]
            //   mv.#no^e1^ni# <=> <Variable> coefs2[4]
            //   mv.#no^e2^ni# <=> <Variable> coefs2[5]
            //   mv.#e1^e2^ni# <=> <Variable> coefs2[6]
            //   mv.#no^e3^ni# <=> <Variable> coefs2[7]
            //   mv.#e1^e3^ni# <=> <Variable> coefs2[8]
            //   mv.#e2^e3^ni# <=> <Variable> coefs2[9]
            
            double[] tempArray = new double[32];
            
            tempArray[0] = Math.Pow(2, -0.5);
            tempArray[1] = (coefs1[2] * tempArray[0]);
            tempArray[2] = (-1 * coefs1[9] * tempArray[0]);
            tempArray[3] = (tempArray[1] + tempArray[2]);
            tempArray[4] = (-1 * coefs2[5] * tempArray[3]);
            tempArray[5] = (coefs1[1] * tempArray[0]);
            tempArray[6] = (-1 * coefs1[8] * tempArray[0]);
            tempArray[7] = (tempArray[5] + tempArray[6]);
            tempArray[8] = (-1 * coefs2[4] * tempArray[7]);
            tempArray[4] = (tempArray[4] + tempArray[8]);
            tempArray[8] = (-1 * coefs1[0] * tempArray[0]);
            tempArray[9] = (-1 * coefs1[6] * tempArray[0]);
            tempArray[10] = (tempArray[8] + tempArray[9]);
            tempArray[11] = (-1 * coefs2[3] * tempArray[10]);
            tempArray[4] = (tempArray[4] + tempArray[11]);
            tempArray[11] = (coefs2[2] * tempArray[0]);
            tempArray[12] = (-1 * coefs2[9] * tempArray[0]);
            tempArray[11] = (tempArray[11] + tempArray[12]);
            tempArray[13] = (coefs1[5] * tempArray[11]);
            tempArray[4] = (tempArray[4] + tempArray[13]);
            tempArray[13] = (coefs2[1] * tempArray[0]);
            tempArray[14] = (-1 * coefs2[8] * tempArray[0]);
            tempArray[13] = (tempArray[13] + tempArray[14]);
            tempArray[15] = (coefs1[4] * tempArray[13]);
            tempArray[4] = (tempArray[4] + tempArray[15]);
            tempArray[15] = (-1 * coefs2[0] * tempArray[0]);
            tempArray[16] = (-1 * coefs2[6] * tempArray[0]);
            tempArray[15] = (tempArray[15] + tempArray[16]);
            tempArray[17] = (coefs1[3] * tempArray[15]);
            tempArray[4] = (tempArray[4] + tempArray[17]);
            tempArray[17] = (-1 * tempArray[0] * tempArray[4]);
            tempArray[18] = (-1 * coefs1[2] * tempArray[0]);
            tempArray[2] = (tempArray[2] + tempArray[18]);
            tempArray[19] = (coefs2[5] * tempArray[2]);
            tempArray[20] = (-1 * coefs1[1] * tempArray[0]);
            tempArray[6] = (tempArray[6] + tempArray[20]);
            tempArray[21] = (coefs2[4] * tempArray[6]);
            tempArray[19] = (tempArray[19] + tempArray[21]);
            tempArray[21] = (coefs1[0] * tempArray[0]);
            tempArray[9] = (tempArray[9] + tempArray[21]);
            tempArray[22] = (-1 * coefs2[3] * tempArray[9]);
            tempArray[19] = (tempArray[19] + tempArray[22]);
            tempArray[22] = (-1 * coefs2[2] * tempArray[0]);
            tempArray[12] = (tempArray[12] + tempArray[22]);
            tempArray[22] = (-1 * coefs1[5] * tempArray[12]);
            tempArray[19] = (tempArray[19] + tempArray[22]);
            tempArray[22] = (-1 * coefs2[1] * tempArray[0]);
            tempArray[14] = (tempArray[14] + tempArray[22]);
            tempArray[22] = (-1 * coefs1[4] * tempArray[14]);
            tempArray[19] = (tempArray[19] + tempArray[22]);
            tempArray[22] = (coefs2[0] * tempArray[0]);
            tempArray[16] = (tempArray[16] + tempArray[22]);
            tempArray[22] = (coefs1[3] * tempArray[16]);
            tempArray[19] = (tempArray[19] + tempArray[22]);
            tempArray[19] = (tempArray[0] * tempArray[19]);
            tempArray[17] = (tempArray[17] + tempArray[19]);
            tempArray[22] = (-1 * tempArray[0] * tempArray[17]);
            tempArray[4] = (tempArray[0] * tempArray[4]);
            tempArray[4] = (tempArray[19] + tempArray[4]);
            tempArray[4] = (tempArray[0] * tempArray[4]);
            tempArray[19] = (tempArray[22] + tempArray[4]);
            tempArray[22] = (coefs2[7] * tempArray[3]);
            tempArray[23] = (coefs2[3] * tempArray[6]);
            tempArray[22] = (tempArray[22] + tempArray[23]);
            tempArray[23] = (-1 * coefs2[4] * tempArray[9]);
            tempArray[22] = (tempArray[22] + tempArray[23]);
            tempArray[23] = (-1 * coefs1[7] * tempArray[11]);
            tempArray[22] = (tempArray[22] + tempArray[23]);
            tempArray[23] = (-1 * coefs1[3] * tempArray[14]);
            tempArray[22] = (tempArray[22] + tempArray[23]);
            tempArray[23] = (coefs1[4] * tempArray[16]);
            tempArray[22] = (tempArray[22] + tempArray[23]);
            tempArray[23] = (-1 * tempArray[0] * tempArray[22]);
            tempArray[24] = (-1 * coefs2[7] * tempArray[2]);
            tempArray[25] = (coefs2[3] * tempArray[7]);
            tempArray[24] = (tempArray[24] + tempArray[25]);
            tempArray[25] = (coefs2[4] * tempArray[10]);
            tempArray[24] = (tempArray[24] + tempArray[25]);
            tempArray[25] = (coefs1[7] * tempArray[12]);
            tempArray[24] = (tempArray[24] + tempArray[25]);
            tempArray[25] = (-1 * coefs1[3] * tempArray[13]);
            tempArray[24] = (tempArray[24] + tempArray[25]);
            tempArray[25] = (-1 * coefs1[4] * tempArray[15]);
            tempArray[24] = (tempArray[24] + tempArray[25]);
            tempArray[24] = (tempArray[0] * tempArray[24]);
            tempArray[23] = (tempArray[23] + tempArray[24]);
            tempArray[25] = (tempArray[0] * tempArray[23]);
            tempArray[22] = (tempArray[0] * tempArray[22]);
            tempArray[22] = (tempArray[24] + tempArray[22]);
            tempArray[22] = (tempArray[0] * tempArray[22]);
            tempArray[24] = (tempArray[25] + tempArray[22]);
            tempArray[25] = (coefs2[3] * tempArray[2]);
            tempArray[26] = (-1 * coefs2[7] * tempArray[7]);
            tempArray[25] = (tempArray[25] + tempArray[26]);
            tempArray[26] = (-1 * coefs2[5] * tempArray[9]);
            tempArray[25] = (tempArray[25] + tempArray[26]);
            tempArray[26] = (-1 * coefs1[3] * tempArray[12]);
            tempArray[25] = (tempArray[25] + tempArray[26]);
            tempArray[26] = (coefs1[7] * tempArray[13]);
            tempArray[25] = (tempArray[25] + tempArray[26]);
            tempArray[26] = (coefs1[5] * tempArray[16]);
            tempArray[25] = (tempArray[25] + tempArray[26]);
            tempArray[26] = (-1 * tempArray[0] * tempArray[25]);
            tempArray[27] = (coefs2[3] * tempArray[3]);
            tempArray[28] = (coefs2[7] * tempArray[6]);
            tempArray[27] = (tempArray[27] + tempArray[28]);
            tempArray[28] = (coefs2[5] * tempArray[10]);
            tempArray[27] = (tempArray[27] + tempArray[28]);
            tempArray[28] = (-1 * coefs1[3] * tempArray[11]);
            tempArray[27] = (tempArray[27] + tempArray[28]);
            tempArray[28] = (-1 * coefs1[7] * tempArray[14]);
            tempArray[27] = (tempArray[27] + tempArray[28]);
            tempArray[28] = (-1 * coefs1[5] * tempArray[15]);
            tempArray[27] = (tempArray[27] + tempArray[28]);
            tempArray[27] = (tempArray[0] * tempArray[27]);
            tempArray[26] = (tempArray[26] + tempArray[27]);
            tempArray[28] = (tempArray[0] * tempArray[26]);
            tempArray[25] = (tempArray[0] * tempArray[25]);
            tempArray[25] = (tempArray[27] + tempArray[25]);
            tempArray[25] = (tempArray[0] * tempArray[25]);
            tempArray[27] = (tempArray[28] + tempArray[25]);
            tempArray[28] = (coefs1[9] * tempArray[0]);
            tempArray[1] = (tempArray[1] + tempArray[28]);
            tempArray[29] = (-1 * coefs1[5] * coefs2[3]);
            tempArray[30] = (-1 * coefs1[3] * coefs2[5]);
            tempArray[29] = (tempArray[29] + tempArray[30]);
            tempArray[30] = (tempArray[9] * tempArray[12]);
            tempArray[29] = (tempArray[29] + tempArray[30]);
            tempArray[30] = (-1 * tempArray[10] * tempArray[11]);
            tempArray[29] = (tempArray[29] + tempArray[30]);
            tempArray[30] = (-1 * tempArray[3] * tempArray[15]);
            tempArray[29] = (tempArray[29] + tempArray[30]);
            tempArray[30] = (tempArray[2] * tempArray[16]);
            tempArray[29] = (tempArray[29] + tempArray[30]);
            tempArray[18] = (tempArray[18] + tempArray[28]);
            tempArray[28] = (coefs1[8] * tempArray[0]);
            tempArray[5] = (tempArray[5] + tempArray[28]);
            tempArray[30] = (-1 * coefs1[4] * coefs2[3]);
            tempArray[31] = (-1 * coefs1[3] * coefs2[4]);
            tempArray[30] = (tempArray[30] + tempArray[31]);
            tempArray[31] = (tempArray[9] * tempArray[14]);
            tempArray[30] = (tempArray[30] + tempArray[31]);
            tempArray[31] = (-1 * tempArray[10] * tempArray[13]);
            tempArray[30] = (tempArray[30] + tempArray[31]);
            tempArray[31] = (-1 * tempArray[7] * tempArray[15]);
            tempArray[30] = (tempArray[30] + tempArray[31]);
            tempArray[31] = (tempArray[6] * tempArray[16]);
            tempArray[30] = (tempArray[30] + tempArray[31]);
            tempArray[20] = (tempArray[20] + tempArray[28]);
            tempArray[28] = (coefs1[3] * coefs2[3]);
            tempArray[31] = (coefs1[4] * coefs2[4]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (coefs1[5] * coefs2[5]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (coefs1[7] * coefs2[7]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (tempArray[2] * tempArray[12]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (tempArray[3] * tempArray[11]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (tempArray[6] * tempArray[14]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (tempArray[7] * tempArray[13]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (tempArray[10] * tempArray[15]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (tempArray[9] * tempArray[16]);
            tempArray[28] = (tempArray[28] + tempArray[31]);
            tempArray[31] = (coefs1[6] * tempArray[0]);
            tempArray[21] = (tempArray[21] + tempArray[31]);
            tempArray[8] = (tempArray[8] + tempArray[31]);
            tempArray[17] = (tempArray[0] * tempArray[17]);
            tempArray[4] = (tempArray[4] + tempArray[17]);
            tempArray[17] = (-1 * tempArray[0] * tempArray[23]);
            tempArray[17] = (tempArray[22] + tempArray[17]);
            tempArray[22] = (-1 * tempArray[0] * tempArray[26]);
            tempArray[22] = (tempArray[25] + tempArray[22]);
            tempArray[23] = (coefs1[7] * coefs2[3]);
            tempArray[25] = (coefs1[3] * coefs2[7]);
            tempArray[23] = (tempArray[23] + tempArray[25]);
            tempArray[7] = (-1 * tempArray[7] * tempArray[12]);
            tempArray[7] = (tempArray[23] + tempArray[7]);
            tempArray[6] = (tempArray[11] * tempArray[6]);
            tempArray[6] = (tempArray[7] + tempArray[6]);
            tempArray[3] = (tempArray[3] * tempArray[14]);
            tempArray[3] = (tempArray[6] + tempArray[3]);
            tempArray[2] = (-1 * tempArray[13] * tempArray[2]);
            tempArray[2] = (tempArray[3] + tempArray[2]);
            tempArray[3] = (coefs1[3] * tempArray[28]);
            tempArray[6] = (-1 * coefs1[4] * tempArray[30]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (coefs1[5] * tempArray[29]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (-1 * coefs1[7] * tempArray[2]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[1] * tempArray[22]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[27] * tempArray[18]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (tempArray[5] * tempArray[17]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (tempArray[24] * tempArray[20]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[19] * tempArray[21]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[8] * tempArray[4]);
            c[3] = (tempArray[3] + tempArray[6]);
            tempArray[3] = (coefs2[4] * tempArray[3]);
            tempArray[6] = (-1 * coefs2[5] * tempArray[7]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (coefs2[7] * tempArray[9]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (coefs1[4] * tempArray[11]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (-1 * coefs1[5] * tempArray[13]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (coefs1[7] * tempArray[16]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (tempArray[0] * tempArray[3]);
            tempArray[7] = (-1 * coefs2[4] * tempArray[2]);
            tempArray[11] = (coefs2[5] * tempArray[6]);
            tempArray[7] = (tempArray[7] + tempArray[11]);
            tempArray[11] = (-1 * coefs2[7] * tempArray[10]);
            tempArray[7] = (tempArray[7] + tempArray[11]);
            tempArray[11] = (-1 * coefs1[4] * tempArray[12]);
            tempArray[7] = (tempArray[7] + tempArray[11]);
            tempArray[11] = (coefs1[5] * tempArray[14]);
            tempArray[7] = (tempArray[7] + tempArray[11]);
            tempArray[11] = (-1 * coefs1[7] * tempArray[15]);
            tempArray[7] = (tempArray[7] + tempArray[11]);
            tempArray[7] = (-1 * tempArray[0] * tempArray[7]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[11] = (-1 * tempArray[0] * tempArray[6]);
            tempArray[3] = (-1 * tempArray[0] * tempArray[3]);
            tempArray[3] = (tempArray[7] + tempArray[3]);
            tempArray[3] = (-1 * tempArray[0] * tempArray[3]);
            tempArray[7] = (tempArray[11] + tempArray[3]);
            tempArray[11] = (-1 * coefs1[7] * coefs2[4]);
            tempArray[12] = (coefs1[4] * coefs2[7]);
            tempArray[11] = (tempArray[11] + tempArray[12]);
            tempArray[12] = (-1 * tempArray[10] * tempArray[12]);
            tempArray[11] = (tempArray[11] + tempArray[12]);
            tempArray[12] = (-1 * tempArray[11] * tempArray[9]);
            tempArray[11] = (tempArray[11] + tempArray[12]);
            tempArray[12] = (tempArray[15] * tempArray[2]);
            tempArray[11] = (tempArray[11] + tempArray[12]);
            tempArray[12] = (tempArray[3] * tempArray[16]);
            tempArray[11] = (tempArray[11] + tempArray[12]);
            tempArray[6] = (tempArray[0] * tempArray[6]);
            tempArray[3] = (tempArray[3] + tempArray[6]);
            tempArray[6] = (-1 * coefs1[5] * coefs2[4]);
            tempArray[12] = (coefs1[4] * coefs2[5]);
            tempArray[6] = (tempArray[6] + tempArray[12]);
            tempArray[12] = (tempArray[6] * tempArray[12]);
            tempArray[6] = (tempArray[6] + tempArray[12]);
            tempArray[12] = (tempArray[7] * tempArray[11]);
            tempArray[6] = (tempArray[6] + tempArray[12]);
            tempArray[12] = (-1 * tempArray[2] * tempArray[14]);
            tempArray[6] = (tempArray[6] + tempArray[12]);
            tempArray[12] = (-1 * tempArray[3] * tempArray[13]);
            tempArray[6] = (tempArray[6] + tempArray[12]);
            tempArray[12] = (coefs1[4] * tempArray[28]);
            tempArray[13] = (-1 * coefs1[3] * tempArray[30]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * coefs1[7] * tempArray[11]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * coefs1[5] * tempArray[6]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * tempArray[7] * tempArray[1]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (tempArray[18] * tempArray[3]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (tempArray[5] * tempArray[4]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * tempArray[19] * tempArray[20]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (tempArray[24] * tempArray[21]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * tempArray[8] * tempArray[17]);
            c[4] = (tempArray[12] + tempArray[13]);
            tempArray[12] = (coefs1[7] * coefs2[5]);
            tempArray[13] = (-1 * coefs1[5] * coefs2[7]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * tempArray[10] * tempArray[14]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * tempArray[13] * tempArray[9]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (tempArray[15] * tempArray[6]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (tempArray[7] * tempArray[16]);
            tempArray[12] = (tempArray[12] + tempArray[13]);
            tempArray[13] = (-1 * coefs1[5] * tempArray[28]);
            tempArray[14] = (coefs1[7] * tempArray[12]);
            tempArray[13] = (tempArray[13] + tempArray[14]);
            tempArray[14] = (-1 * coefs1[3] * tempArray[29]);
            tempArray[13] = (tempArray[13] + tempArray[14]);
            tempArray[6] = (-1 * coefs1[4] * tempArray[6]);
            tempArray[6] = (tempArray[13] + tempArray[6]);
            tempArray[4] = (-1 * tempArray[1] * tempArray[4]);
            tempArray[4] = (tempArray[6] + tempArray[4]);
            tempArray[6] = (tempArray[19] * tempArray[18]);
            tempArray[4] = (tempArray[4] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[7] * tempArray[5]);
            tempArray[4] = (tempArray[4] + tempArray[6]);
            tempArray[6] = (tempArray[20] * tempArray[3]);
            tempArray[4] = (tempArray[4] + tempArray[6]);
            tempArray[6] = (tempArray[27] * tempArray[21]);
            tempArray[4] = (tempArray[4] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[8] * tempArray[22]);
            c[5] = (tempArray[4] + tempArray[6]);
            tempArray[4] = (-1 * coefs1[7] * tempArray[28]);
            tempArray[6] = (-1 * coefs1[5] * tempArray[12]);
            tempArray[4] = (tempArray[4] + tempArray[6]);
            tempArray[6] = (-1 * coefs1[4] * tempArray[11]);
            tempArray[4] = (tempArray[4] + tempArray[6]);
            tempArray[2] = (coefs1[3] * tempArray[2]);
            tempArray[2] = (tempArray[4] + tempArray[2]);
            tempArray[1] = (tempArray[24] * tempArray[1]);
            tempArray[1] = (tempArray[2] + tempArray[1]);
            tempArray[2] = (-1 * tempArray[18] * tempArray[17]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (tempArray[27] * tempArray[5]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (-1 * tempArray[20] * tempArray[22]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (tempArray[7] * tempArray[21]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (-1 * tempArray[8] * tempArray[3]);
            c[7] = (tempArray[1] + tempArray[2]);
            tempArray[1] = (coefs1[3] * tempArray[19]);
            tempArray[2] = (-1 * coefs1[4] * tempArray[24]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (coefs1[5] * tempArray[27]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (-1 * coefs1[7] * tempArray[7]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (tempArray[11] * tempArray[1]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (tempArray[29] * tempArray[18]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (-1 * tempArray[12] * tempArray[5]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (-1 * tempArray[30] * tempArray[20]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (tempArray[28] * tempArray[21]);
            tempArray[1] = (tempArray[1] + tempArray[2]);
            tempArray[2] = (-1 * tempArray[3] * tempArray[12]);
            tempArray[3] = (tempArray[11] * tempArray[2]);
            tempArray[2] = (tempArray[2] + tempArray[3]);
            tempArray[3] = (-1 * tempArray[7] * tempArray[14]);
            tempArray[2] = (tempArray[2] + tempArray[3]);
            tempArray[3] = (tempArray[13] * tempArray[6]);
            tempArray[2] = (tempArray[2] + tempArray[3]);
            tempArray[3] = (-1 * tempArray[15] * tempArray[9]);
            tempArray[2] = (tempArray[2] + tempArray[3]);
            tempArray[3] = (tempArray[10] * tempArray[16]);
            tempArray[2] = (tempArray[2] + tempArray[3]);
            tempArray[3] = (tempArray[2] * tempArray[8]);
            tempArray[1] = (tempArray[1] + tempArray[3]);
            tempArray[1] = (-1 * tempArray[0] * tempArray[1]);
            tempArray[3] = (coefs1[3] * tempArray[4]);
            tempArray[4] = (coefs1[4] * tempArray[17]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (-1 * coefs1[5] * tempArray[22]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (coefs1[7] * tempArray[3]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (-1 * tempArray[1] * tempArray[29]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (tempArray[11] * tempArray[18]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (tempArray[5] * tempArray[30]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (-1 * tempArray[12] * tempArray[20]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (-1 * tempArray[21] * tempArray[2]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (tempArray[28] * tempArray[8]);
            tempArray[3] = (tempArray[3] + tempArray[4]);
            tempArray[4] = (tempArray[0] * tempArray[3]);
            tempArray[4] = (tempArray[1] + tempArray[4]);
            c[0] = (-1 * tempArray[4]);
            tempArray[4] = (-1 * coefs1[4] * tempArray[4]);
            tempArray[5] = (-1 * coefs1[3] * tempArray[17]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (coefs1[7] * tempArray[27]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (coefs1[5] * tempArray[7]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (-1 * tempArray[1] * tempArray[6]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (-1 * tempArray[18] * tempArray[2]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (tempArray[5] * tempArray[28]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (tempArray[20] * tempArray[2]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (tempArray[12] * tempArray[21]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[5] = (tempArray[30] * tempArray[8]);
            tempArray[4] = (tempArray[4] + tempArray[5]);
            tempArray[4] = (-1 * tempArray[0] * tempArray[4]);
            tempArray[5] = (coefs1[4] * tempArray[19]);
            tempArray[6] = (-1 * coefs1[3] * tempArray[24]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (-1 * coefs1[7] * tempArray[22]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (-1 * coefs1[5] * tempArray[3]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (tempArray[1] * tempArray[2]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[18] * tempArray[6]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[5] * tempArray[2]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (tempArray[20] * tempArray[28]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (-1 * tempArray[30] * tempArray[21]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (tempArray[12] * tempArray[8]);
            tempArray[5] = (tempArray[5] + tempArray[6]);
            tempArray[6] = (tempArray[0] * tempArray[5]);
            tempArray[6] = (tempArray[4] + tempArray[6]);
            c[1] = (-1 * tempArray[6]);
            tempArray[6] = (coefs1[5] * tempArray[4]);
            tempArray[7] = (-1 * coefs1[7] * tempArray[24]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (-1 * coefs1[3] * tempArray[22]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (coefs1[4] * tempArray[7]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (-1 * tempArray[1] * tempArray[28]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (-1 * tempArray[18] * tempArray[2]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (-1 * tempArray[5] * tempArray[6]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (-1 * tempArray[20] * tempArray[2]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (tempArray[11] * tempArray[21]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[7] = (tempArray[29] * tempArray[8]);
            tempArray[6] = (tempArray[6] + tempArray[7]);
            tempArray[6] = (-1 * tempArray[0] * tempArray[6]);
            tempArray[7] = (-1 * coefs1[5] * tempArray[19]);
            tempArray[8] = (coefs1[7] * tempArray[17]);
            tempArray[7] = (tempArray[7] + tempArray[8]);
            tempArray[8] = (-1 * coefs1[3] * tempArray[27]);
            tempArray[7] = (tempArray[7] + tempArray[8]);
            tempArray[8] = (-1 * coefs1[4] * tempArray[3]);
            tempArray[7] = (tempArray[7] + tempArray[8]);
            tempArray[2] = (tempArray[1] * tempArray[2]);
            tempArray[2] = (tempArray[7] + tempArray[2]);
            tempArray[7] = (-1 * tempArray[18] * tempArray[28]);
            tempArray[2] = (tempArray[2] + tempArray[7]);
            tempArray[7] = (tempArray[5] * tempArray[2]);
            tempArray[2] = (tempArray[2] + tempArray[7]);
            tempArray[7] = (-1 * tempArray[20] * tempArray[6]);
            tempArray[2] = (tempArray[2] + tempArray[7]);
            tempArray[7] = (-1 * tempArray[29] * tempArray[21]);
            tempArray[2] = (tempArray[2] + tempArray[7]);
            tempArray[7] = (tempArray[11] * tempArray[8]);
            tempArray[2] = (tempArray[2] + tempArray[7]);
            tempArray[7] = (tempArray[0] * tempArray[2]);
            tempArray[7] = (tempArray[6] + tempArray[7]);
            c[2] = (-1 * tempArray[7]);
            tempArray[3] = (-1 * tempArray[0] * tempArray[3]);
            tempArray[1] = (tempArray[1] + tempArray[3]);
            c[6] = (-1 * tempArray[1]);
            tempArray[1] = (-1 * tempArray[0] * tempArray[5]);
            tempArray[1] = (tempArray[4] + tempArray[1]);
            c[8] = (-1 * tempArray[1]);
            tempArray[0] = (-1 * tempArray[0] * tempArray[2]);
            tempArray[0] = (tempArray[6] + tempArray[0]);
            c[9] = (-1 * tempArray[0]);
            
            //Finish GMac Macro Code Generation, 2015-12-20T21:46:55.4501797+02:00
            
            return c;
        }
        
        
    }
}
